name: Setup python
description: Setup python, poetry and caching

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - run: pipx install poetry
      shell: bash

    - uses: actions/cache@v4
      with:
        path: ${{ env.POETRY_CACHE_DIR }}
        key: ${{ runner.os }}-poetry-v1-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-v1-
